### ISSUE TITLE
use mamba instead of conda if available

### ISSUE THREAD

**Issue by hzpc-joostk** [mariusvniekerk/condax#11]
Hi! Thanks for developing your awesome tool! Are you planning to rely on `mamba` in case it is installed? It is very fast compared to `conda` and because of that may be well suited for your project.

Reading through your package, it may be as simple as adding the following at the start in function `condax.conda.ensure_conda()`:

```python
def ensure_conda():
    mamba_executable = shutil.which("mamba")
    if mamba_executable:
        return mamba_executable
```

**Comment by mariusvniekerk** [comment]
Yeah this can probably be refactored to use ensureconda (another library that does a lot of that kind of stuff).  Do you want to submit a pull request?
