### ISSUE TITLE
Allow specifying Python version when installing a package

### ISSUE THREAD

**Issue by pawamoy** [mariusvniekerk/condax#3]
I'm on Windows, with an Anaconda installation.

- `python -V` gives me 3.7.3
- `condax install poetry` installs poetry in a venv using python 3.8.0
- I need python 3.6 at work

I would like an option to do something like `condax install --python=3.6 poetry`.

**Comment by pawamoy** [comment]
Not using condax anymore, feel free to reopen :slightly_smiling_face:

**Comment by mforbes** [comment]
Please re-open.  This is a show-stopper in some cases when the package does not properly pin the version of python.

**Comment by pawamoy** [comment]
Would you mind opening a new issue? I'd like to avoid having this tied to my username/issues (just for tidiness reasons).
